### ISSUE TITLE
Error: Cannot find module './promisified-host-validator'

### ISSUE THREAD

**Issue by fmichaud** [9fv/node-host-validator#1]
```
Error: Cannot find module './promisified-host-validator'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/fmichaud/.node_modules/entity-host/node_modules/host-validator/lib/index.js:12:36)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/fmichaud/.node_modules/entity-host/lib/host.js:11:40)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/fmichaud/.node_modules/entity-host/test/host.test.js:12:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at /home/fmichaud/.node_modules/repeat-until-success/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/fmichaud/.node_modules/repeat-until-success/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/home/fmichaud/.node_modules/repeat-until-success/node_modules/mocha/lib/mocha.js:536:10)
    at Object.<anonymous> (/home/fmichaud/.node_modules/repeat-until-success/node_modules/mocha/bin/_mocha:582:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3

Process finished with exit code 1
```

**Comment by fmichaud** [comment]
Fixed
